[package]
name = "asy"
version = "0.1.0"
edition = "2021"

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
log = "0.4.14"
env_logger = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"
hex = "0.4.3"